from schemas.regiao import RegiaoSchema, ListagemRegioesSchema, apresenta_regioes, RegiaoViewSchema, apresenta_regiao
from schemas.operadora import OperadoraBuscaSchema, OperadoraRegiaoBuscaSchema, OperadoraSchema, ListagemOperadorasSchema, apresenta_operadoras, OperadoraViewSchema, apresenta_operadora
from schemas.consulta import ConsultaSchema, ListagemConsultasSchema, ListagemConsultasLimitadasSchema, ConsultaDelSchema, ConsultaBuscaSchema, apresenta_consultas, apresenta_consultas_limitadas, ConsultaViewSchema, apresenta_consulta
from schemas.error import ErrorSchema
